### ISSUE TITLE
Emphasize the tag name, not the SHA checksum

### ISSUE THREAD

**Issue by irasnyd** [Distelli/europa#5]
Pretty web interfaces are made for humans. Humans work better with human-friendly tag names than with long hexadecimal strings representing SHA checksums.

In the tags view, the tag name (`latest`, etc.) should be the first thing in the table, rather than the checksum. Humans care about the tag name, not the checksum.

**Comment by samheutmaker** [comment]
Thanks for the feedback! We welcome pull requests, but I can also prioritize this and have an updated version out shortly.

**Comment by samheutmaker** [comment]
View pull request here: https://github.com/Distelli/europa/pull/11

**Comment by samheutmaker** [comment]
Fixed by https://github.com/Distelli/europa/pull/11
